#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker pull $DOCKER_USERNAME/bmborrowdjango_web
docker tag bmborrowdjango_web $DOCKER_USERNAME/bmborrowdjango_web
docker push $DOCKER_USERNAME/bmborrowdjango_web